services:
  postgres:
    image: postgres:17
    container_name: meeting-room-postgres
    environment:
      POSTGRES_DB: meeting_room_db
      POSTGRES_USER: meeting_user
      POSTGRES_PASSWORD: meeting_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: